-- CREATE TABLE biz (id SERIAL PRIMARY KEY,biz_name VARCHAR UNIQUE);
CREATE TABLE VENDOR(ID SERIAL PRIMARY KEY,
EXTERNAL_ID VARCHAR,
REQUESTED_BY VARCHAR,
DATUM VARCHAR,
KLANT VARCHAR,
ADRES VARCHAR,
EMAIL VARCHAR,
GSM VARCHAR,
VAT VARCHAR,
CONTACT VARCHAR,
KLANTNR VARCHAR,
FILE bytea,
STATUS VARCHAR
)