-- CREATE TABLE biz (id SERIAL PRIMARY KEY,biz_name VARCHAR UNIQUE);
CREATE TABLE PO(ID SERIAL PRIMARY KEY,
REQUESTED_BY VARCHAR,
DATUM VARCHAR,
COMPANY VARCHAR,
COMPANY_CODE VARCHAR,
SHORT_TEXT VARCHAR,
PO_QUANTITY INT,
OVERALL_LIMIT INT,
GR_EXECUTION_DATE VARCHAR,
ORDER VARCHAR,
STATUS VARCHAR
)