var generatePassword = require("password-generator");
let managers = [
  [{ Name: "Gunther Mergan", Manager: "Jean-Francois Forton" }],
  [{ Name: "Marcel VandenBerge", Manager: "Ivo Schouten" }],
  [{ Name: "Jeroen VanBerkel", Manager: "Ivo Schouten" }],
  [{ Name: "Cindy Eekels", Manager: "Andor DeVries" }],
  [{ Name: "Bob Vandenberghen", Manager: "Jean-Francois Forton" }],
  [{ Name: "Nicolas Dedobbeleer", Manager: "Jean-Francois Forton" }],
  [{ Name: "Bram Hennebert", Manager: "Jean-Francois Forton" }],
  [{ Name: "Steve Oris", Manager: "Jean-Francois Forton" }],
  [{ Name: "Christian Darmont", Manager: "Jean-Francois Forton" }],
  [{ Name: "Frank Mentens", Manager: "Jean-Francois Forton" }],
  [{ Name: "Etienne Delvosalle", Manager: "Jean-Francois Forton" }],
  [{ Name: "Jeroen Decherf", Manager: "Jean-Francois Forton" }],
  [{ Name: "Carlos DeBruijn", Manager: "Ivo Schouten" }],
  [{ Name: "Michiel Vliek", Manager: "Ivo Schouten" }],
  [{ Name: "Wouter Rook", Manager: "Ivo Schouten" }],
  [{ Name: "Arnold Wever", Manager: "Ivo Schouten" }],
  [{ Name: "Oscar Laureijs", Manager: "Ivo Schouten" }],
  [{ Name: "Kevin Markestein", Manager: "Jean-Francois Forton" }],
  [{ Name: "David Goubert", Manager: "Jean-Francois Forton" }],
  [{ Name: "Jurgen DeLeeuw", Manager: "Ivo Schouten" }],
  [{ Name: "Thomas Molendijk", Manager: "Ivo Schouten" }],
  [{ Name: "Marcelino Papperse", Manager: "Ivo Schouten" }],
  [{ Name: "Andor DeVries", Manager: "Ivo Schouten" }],
  [{ Name: "Ivo Schouten", Manager: "Patrick Diepenbach" }],
  [{ Name: "Patrick Diepenbach", Manager: "Mark Smiley" }],
  [{ Name: "Piet Verstraete", Manager: "Patrick Diepenbach" }],
  [{ Name: "Vincent Broertjes", Manager: "Patrick Diepenbach" }],
  [{ Name: "Jean-Christophe Pintiaux", Manager: "Piet Verstraete" }],
  [{ Name: "Kim Maris", Manager: "Piet Verstraete" }],
  [{ Name: "Mario Reverse", Manager: "Piet Verstraete" }],
  [{ Name: "Peter Schaekers", Manager: "Piet Verstraete" }],
  [{ Name: "Robin Roels", Manager: "Piet Verstraete" }],
  [{ Name: "Stefan Sack", Manager: "Piet Verstraete" }],
  [{ Name: "Vincent Lenain", Manager: "Piet Verstraete" }],
  [{ Name: "Vincent Pireyn", Manager: "Piet Verstraete" }],
  [{ Name: "Yves DeWaal", Manager: "Piet Verstraete" }],
  [{ Name: "Adriaan Arkeraats", Manager: "Vincent Broertjes" }],
  [{ Name: "Arno DeJager", Manager: "Vincent Broertjes" }],
  [{ Name: "Duncan DeWith", Manager: "Vincent Broertjes" }],
  [{ Name: "Ken Leysen", Manager: "Patrick Diepenbach" }],
  [{ Name: "Jean-Francois Forton", Manager: "Patrick Diepenbach" }],
  [{ Name: "Martin Van Werkhoven", Manager: "Not Found" }],
  [{ Name: "Paul Kerkhoven", Manager: "Vincent Broertjes" }],
  [{ Name: "Cedric Bicque", Manager: "Ken Leysen" }],
  [{ Name: "Christian Fonteyn", Manager: "Ken Leysen" }],
  [{ Name: "KlaasJan Bosgraaf", Manager: "Ken Leysen" }],
  [{ Name: "Ammaar Basnoe", Manager: "Ken Leysen" }],
  [{ Name: "Robert VanStraten", Manager: "Ken Leysen" }],
  [{ Name: "Sven Pieters", Manager: "Ken Leysen" }],
  [{ Name: "Niek Nijland", Manager: "Ken Leysen" }],
  [{ Name: "Geert Maes", Manager: "Stephane Depret" }],
  [{ Name: "Marleen Vangronsveld", Manager: "Stephane Depret" }],
  [{ Name: "Marlon VanZundert", Manager: "Stephane Depret" }],
  [{ Name: "Michael Soenen", Manager: "Stephane Depret" }],
  [{ Name: "Michael Tistaert", Manager: "Stephane Depret" }],
  [{ Name: "Ronald Westra", Manager: "Stephane Depret" }],
  [{ Name: "Vicky DeDecker", Manager: "Stephane Depret" }],
  [{ Name: "Christelle Marro", Manager: "Stephane Depret" }],
  [{ Name: "Frederic Barzin", Manager: "Christelle Marro" }],
  [{ Name: "Luc Claes", Manager: "Christelle Marro" }],
  [{ Name: "Marc Ghijs", Manager: "Christelle Marro" }],
  [{ Name: "Ronny Callewaert", Manager: "Christelle Marro" }],
  [{ Name: "Hendrik Pieters", Manager: "Eric Nieuwmans" }],
  [{ Name: "Malvin Puts", Manager: "Eric Nieuwmans" }],
  [{ Name: "Niels Groters", Manager: "Eric Nieuwmans" }],
  [{ Name: "Remco Rozing", Manager: "Eric Nieuwmans" }],
  [{ Name: "Eric Nieuwmans", Manager: "Stephane Depret" }],
];
managers.forEach((element) => {
  sales_man = element[0].Name.split(" ");
  pwd = `${generatePassword(2, true, /[\w\d\?\-]/)}${generatePassword(
    3,
    false,
    /([\d])/g
  )}`;
  console.log(`
    insert into users(username, password)
values('${sales_man[0]}.${sales_man[1]}@sbdinc.com','${pwd}');
`);
});
// console.log(credentials.includes('{"username":"team@sbdinc.com","password":"Mechelen2022."}'))
